"""Add file support

Revision ID: 6eddbaa6e3bc
Revises: 9eb238e9bc76
Create Date: 2026-03-19 20:31:36.352496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eddbaa6e3bc'
down_revision: Union[str, Sequence[str], None] = '9eb238e9bc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('telegram_file_id', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('last_reminder_sent', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_reminder_sent')
    op.drop_column('tasks', 'telegram_file_id')
    # ### end Alembic commands ###
