"""Add creator_id to groups

Revision ID: c456891f3fa2
Revises: 6eddbaa6e3bc
Create Date: 2026-03-23 20:38:41.194543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c456891f3fa2'
down_revision: Union[str, Sequence[str], None] = '6eddbaa6e3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'creator_id')
    # ### end Alembic commands ###
